name: OBS_Mylenti

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install core Python packages
        run: pip install pyinstaller flask flask-cors requests

      - name: Clone VietVoice
        run: git clone https://github.com/nguyenvulebinh/VietVoice-TTS.git

      - name: Install VietVoice locally
        run: pip install ./VietVoice-TTS

      - name: Install Bun (Windows)
        if: runner.os == 'Windows'
        run: |
          iwr https://bun.sh/install.ps1 -UseBasicParsing | iex
          echo "$env:USERPROFILE\.bun\bin" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

      - name: Install Bun (Unix)
        if: runner.os != 'Windows'
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Verify Bun install
        run: |
          bun --version
          which bun || echo "bun not found"

      - name: Install frontend dependencies
        run: bun install

      - name: Install nexe locally
        run: bun i nexe -g

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0.5.23
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Generate SHA256 checksums (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mkdir -p checksums
          find src-tauri/target/release/bundle -type f \( -name "*.msi" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.rpm" -o -name "*.dmg" \) \
            -exec sha256sum {} \; > checksums/sha256-${{ runner.os }}.txt

      - name: Generate SHA256 checksums (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path checksums
          Get-ChildItem -Recurse -Path "src-tauri/target/release/bundle" -Include *.msi, *.AppImage, *.deb, *.rpm, *.dmg |
            ForEach-Object {
              $hash = Get-FileHash $_.FullName -Algorithm SHA256
              "$($hash.Hash)  $($_.FullName)"
            } > "checksums/sha256-${{ runner.os }}.txt"


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.AppImage
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.rpm
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.sig
            bin/donate_voice-*
            bin/node_server-*
            checksums/sha256-${{ runner.os }}.txt


      - name: Format SHA256 as Markdown table (Linux/macOS)
        if: runner.os != 'Windows'
        id: format_unix
        run: |
          echo "table<<EOF" >> $GITHUB_OUTPUT
          echo "| File | SHA256 |" >> $GITHUB_OUTPUT
          echo "|------|--------|" >> $GITHUB_OUTPUT
          awk '{printf "| %s | %s |\n", $2, $1}' checksums/sha256-${{ runner.os }}.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Format SHA256 as Markdown table (Windows)
        if: runner.os == 'Windows'
        id: format_win
        shell: pwsh
        run: |
          $lines = Get-Content "checksums/sha256-${{ runner.os }}.txt"
          $table = @()
          $table += "| File | SHA256 |"
          $table += "|------|--------|"
          foreach ($line in $lines) {
            $parts = $line -split '\s+'
            $table += "| $($parts[1]) | $($parts[0]) |"
          }
          "table<<EOF`n$($table -join "`n")`nEOF" >> $env:GITHUB_OUTPUT

      - name: Merge SHA256 table output
        id: format
        shell: bash
        run: |
          if [ -n "${{ steps.format_unix.outputs.table }}" ]; then
            echo "table=${{ steps.format_unix.outputs.table }}" >> $GITHUB_OUTPUT
          else
            echo "table=${{ steps.format_win.outputs.table }}" >> $GITHUB_OUTPUT
          fi

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: .github/changelog-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy .sig files to downloads
        run: |
          mkdir -p downloads
          cp src-tauri/target/release/bundle/**/*.sig downloads/

      - name: Read .sig files with validation
        id: sigs
        shell: bash
        run: |
          VERSION="${{ env.VERSION }}"
          mkdir -p downloads
          WIN_SIG=$(find downloads -name "Mylenti_${VERSION}_x64_en-US.msi.sig" | head -n 1)
          MAC_SIG=$(find downloads -name "Mylenti_${VERSION}_en-US.dmg.sig" | head -n 1)
          LINUX_SIG=$(find downloads -name "Mylenti_${VERSION}_en-US.AppImage.sig" | head -n 1)

          if [ -z "$WIN_SIG" ] || [ -z "$MAC_SIG" ] || [ -z "$LINUX_SIG" ]; then
            echo "❌ Thiếu file chữ ký .sig. Kiểm tra lại tên file hoặc quá trình build."
            exit 1
          fi

          echo "windows_sig=$(cat "$WIN_SIG")" >> $GITHUB_OUTPUT
          echo "macos_sig=$(cat "$MAC_SIG")" >> $GITHUB_OUTPUT
          echo "linux_sig=$(cat "$LINUX_SIG")" >> $GITHUB_OUTPUT

      - name: Generate latest.json
        id: latest_json
        shell: bash
        env:
          VERSION: ${{ env.VERSION }}
          NOTES: ${{ steps.changelog.outputs.changelog }}
          WINDOWS_SIG: ${{ steps.sigs.outputs.windows_sig }}
          MACOS_SIG: ${{ steps.sigs.outputs.macos_sig }}
          LINUX_SIG: ${{ steps.sigs.outputs.linux_sig }}
        run: |
          PUB_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # Escape NOTES safely using base64
          NOTES_B64=$(echo "$NOTES" | base64)

          # Decode and escape inside JSON
          echo "{" > latest.json
          echo "  \"version\": \"$VERSION\"," >> latest.json
          echo "  \"notes\": \"$(echo "$NOTES_B64" | base64 --decode | sed 's/\\/\\\\/g; s/"/\\"/g')\"," >> latest.json
          echo "  \"pub_date\": \"$PUB_DATE\"," >> latest.json
          echo "  \"platforms\": {" >> latest.json
          echo "    \"windows\": {" >> latest.json
          echo "      \"signature\": \"$WINDOWS_SIG\"," >> latest.json
          echo "      \"url\": \"https://github.com/khoiw04/OBS_Mylenti/releases/download/$VERSION/Mylenti_${VERSION}_x64_en-US.msi\"" >> latest.json
          echo "    }," >> latest.json
          echo "    \"macos\": {" >> latest.json
          echo "      \"signature\": \"$MACOS_SIG\"," >> latest.json
          echo "      \"url\": \"https://github.com/khoiw04/OBS_Mylenti/releases/download/$VERSION/Mylenti_${VERSION}_en-US.dmg\"" >> latest.json
          echo "    }," >> latest.json
          echo "    \"linux\": {" >> latest.json
          echo "      \"signature\": \"$LINUX_SIG\"," >> latest.json
          echo "      \"url\": \"https://github.com/khoiw04/OBS_Mylenti/releases/download/$VERSION/Mylenti_${VERSION}_en-US.AppImage\"" >> latest.json
          echo "    }" >> latest.json
          echo "  }" >> latest.json
          echo "}" >> latest.json


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            ${{ steps.changelog.outputs.changelog }}

            ## 🔐 SHA256 Checksums
            ${{ steps.format.outputs.table }}
          files: |
            src-tauri/target/release/bundle/**/*.sig
            latest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}