name: OBS_Mylenti

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install core Python packages
        run: pip install pyinstaller flask flask-cors requests

      - name: Clone VietVoice
        run: git clone https://github.com/nguyenvulebinh/VietVoice-TTS.git

      - name: Install VietVoice locally
        run: pip install ./VietVoice-TTS

      - name: Install Bun (Windows)
        if: runner.os == 'Windows'
        run: |
          iwr https://bun.sh/install.ps1 -UseBasicParsing | iex
          echo "$env:USERPROFILE\.bun\bin" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

      - name: Install Bun (Unix)
        if: runner.os != 'Windows'
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Verify Bun install
        run: |
          bun --version
          which bun || echo "bun not found"

      - name: Install frontend dependencies
        run: bun install

      - name: Install nexe locally
        run: bun i nexe -g

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0.5.23
        with:
          tagName: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}