name: OBS_Mylenti

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install core Python packages
        run: pip install pyinstaller flask flask-cors

      - name: Clone VietVoice
        run: git clone https://github.com/nguyenvulebinh/VietVoice-TTS.git

      - name: Install VietVoice locally
        run: pip install ./VietVoice-TTS

      - name: Install Bun (Windows)
        if: runner.os == 'Windows'
        run: |
          iwr https://bun.sh/install.ps1 -UseBasicParsing | iex
          echo "$env:USERPROFILE\.bun\bin" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

      - name: Install Bun (Unix)
        if: runner.os != 'Windows'
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Verify Bun install
        run: |
          bun --version
          which bun || echo "bun not found"

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0.5.23
        with:
          args: build

      - name: Generate SHA256 checksums
        run: |
          mkdir -p checksums
          find src-tauri/target/release/bundle -type f \( -name "*.msi" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.rpm" -o -name "*.dmg" \) \
            -exec sha256sum {} \; > checksums/sha256-${{ runner.os }}.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.AppImage
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.rpm
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.sig
            bin/donate_voice-*
            bin/node_server-*
            checksums/sha256-${{ runner.os }}.txt